name: note0
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.5
  cryptography: ^2.9.0
  flutter_secure_storage: ^10.0.0
  uuid: ^4.5.3
  google_fonts: ^6.3.2
  intl: ^0.20.2
  gap: ^3.0.1
  flutter_animate: ^4.5.2
  record: ^6.1.1
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  screen_protector: ^1.5.1
  file_picker: ^8.1.7
  youtube_explode_dart: ^2.3.4
  share_plus: ^10.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
